import 'package:flutter/material.dart';
import 'package:trendeo/core/color_app.dart';

ThemeData lightTheme = ThemeData(
  useMaterial3: true,
  colorScheme: lightColorScheme,
);

ThemeData darkTheme = ThemeData(
  useMaterial3: true,
  colorScheme: darkColorScheme,
);

ColorScheme lightColorScheme = ColorScheme(
  brightness: Brightness.light,
  primary: ColorApp.lightPrimaryColor,
  onPrimary: ColorApp.lightBackgroundColor,
  primaryContainer: ColorApp.lightBackgroundColor,
  onPrimaryContainer: ColorApp.lightAuxiliaryColor,
  secondary: ColorApp.lightAuxiliaryColor,
  onSecondary: const Color(0xFFFFFFFF),
  secondaryContainer: const Color(0xFFE8DEF8),
  onSecondaryContainer: const Color(0xFF1D192B),
  tertiary: const Color(0xFF7D5260),
  onTertiary: const Color(0xFFFFFFFF),
  tertiaryContainer: const Color(0xFFFFD8E4),
  onTertiaryContainer: const Color(0xFF31111D),
  error: const Color(0xFFB3261E),
  onError: const Color(0xFFFFFFFF),
  errorContainer: const Color(0xFFF9DEDC),
  onErrorContainer: const Color(0xFF410E0B),
  outline: const Color(0xFF79747E),
  background: const Color(0xFFFFFBFE),
  onBackground: const Color(0xFF1C1B1F),
  surface: const Color(0xFFFFFBFE),
  onSurface: const Color(0xFF1C1B1F),
  surfaceVariant: const Color(0xFFE7E0EC),
  onSurfaceVariant: const Color(0xFF49454F),
  inverseSurface: const Color(0xFF313033),
  onInverseSurface: const Color(0xFFF4EFF4),
  inversePrimary: const Color(0xFFD0BCFF),
  shadow: const Color(0xFF000000),
  surfaceTint: const Color(0xFF6750A4),
  outlineVariant: const Color(0xFFCAC4D0),
  scrim: const Color(0xFF000000),
);

ColorScheme darkColorScheme = ColorScheme(
  brightness: Brightness.dark,
  primary: ColorApp.darkPrimaryColor,
  onPrimary: ColorApp.darkBackgroundColor,
  primaryContainer: ColorApp.darkBackgroundColor,
  onPrimaryContainer: ColorApp.darkAuxiliaryColor,
  secondary: ColorApp.darkAuxiliaryColor,
  onSecondary: const Color(0xFF332D41),
  secondaryContainer: const Color(0xFF4A4458),
  onSecondaryContainer: const Color(0xFFE8DEF8),
  tertiary: const Color(0xFFEFB8C8),
  onTertiary: const Color(0xFF492532),
  tertiaryContainer: const Color(0xFF633B48),
  onTertiaryContainer: const Color(0xFFFFD8E4),
  error: const Color(0xFFF2B8B5),
  onError: const Color(0xFF601410),
  errorContainer: const Color(0xFF8C1D18),
  onErrorContainer: const Color(0xFFF9DEDC),
  outline: const Color(0xFF938F99),
  background: const Color(0xFF1C1B1F),
  onBackground: const Color(0xFFE6E1E5),
  surface: const Color(0xFF1C1B1F),
  onSurface: const Color(0xFFE6E1E5),
  surfaceVariant: const Color(0xFF49454F),
  onSurfaceVariant: const Color(0xFFCAC4D0),
  inverseSurface: const Color(0xFFE6E1E5),
  onInverseSurface: const Color(0xFF313033),
  inversePrimary: const Color(0xFF6750A4),
  shadow: const Color(0xFFffffff),
  surfaceTint: const Color(0xFFD0BCFF),
  outlineVariant: const Color(0xFF49454F),
  scrim: const Color(0xFF000000),
);
